name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build JS & Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install JS dependencies
        run: pnpm install --no-frozen-lockfile

      # Menggunakan --recursive agar pnpm otomatis mengurutkan build dari core ke react
      - name: Build packages
        run: pnpm -r run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true

      - name: Publish packages to npm
        run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
